#!/usr/bin/env node
/**
 * Build script to convert WOFF2 fonts to base64 embedded data URIs
 * Run this script to generate fontEmbeds.ts with base64 font data
 */

const fs = require('fs');
const path = require('path');

const FONTS_DIR = path.join(__dirname, '../src/html/fonts');
const OUTPUT_FILE = path.join(__dirname, '../src/html/fontEmbeds.ts');

// Map of weight numbers to weight names (must match fontCollector.ts)
const WEIGHT_NAMES = {
  100: 'Thin',
  200: 'ExtraLight',
  300: 'Light',
  400: 'Regular',
  500: 'Medium',
  600: 'SemiBold',
  700: 'Bold',
  800: 'ExtraBold',
  900: 'Black',
};

function generateFontEmbeds() {
  console.log('🔤 Generating base64 font embeds...\n');

  // Read all .woff2 files from fonts directory
  const fontFiles = fs.readdirSync(FONTS_DIR).filter(file => file.endsWith('.woff2'));

  if (fontFiles.length === 0) {
    console.error('❌ No .woff2 files found in', FONTS_DIR);
    process.exit(1);
  }

  const fontEmbeds = {};

  fontFiles.forEach(fileName => {
    const filePath = path.join(FONTS_DIR, fileName);
    const fontBuffer = fs.readFileSync(filePath);
    const base64 = fontBuffer.toString('base64');
    const dataUri = `data:font/woff2;base64,${base64}`;

    // Extract font family and weight from filename
    // Expected format: FamilyName-WeightName.woff2
    const match = fileName.match(/^(.+?)-(.+?)\.woff2$/);
    if (match) {
      const [, family, weightName] = match;

      // Find weight number from weight name
      const weight = Object.entries(WEIGHT_NAMES).find(
        ([, name]) => name === weightName
      )?.[0] || '400';

      const key = `${family}-${weight}`;
      fontEmbeds[key] = {
        family,
        weight: parseInt(weight),
        dataUri,
        size: fontBuffer.length,
      };

      console.log(`✓ ${fileName} → ${key} (${(fontBuffer.length / 1024).toFixed(1)}KB)`);
    } else {
      console.warn(`⚠️  Skipping ${fileName} - unexpected filename format`);
    }
  });

  // Generate TypeScript file
  const tsContent = `/**
 * Auto-generated base64 font embeds
 * Generated by: packages/backend/scripts/generateFontEmbeds.js
 * DO NOT EDIT MANUALLY - Run 'node scripts/generateFontEmbeds.js' to regenerate
 */

export interface FontEmbed {
  family: string;
  weight: number;
  dataUri: string;
  size: number;
}

export const fontEmbeds: Record<string, FontEmbed> = ${JSON.stringify(fontEmbeds, null, 2)};

/**
 * Get base64 data URI for a font family and weight
 */
export function getFontDataUri(family: string, weight: number): string | null {
  const key = \`\${family}-\${weight}\`;
  return fontEmbeds[key]?.dataUri || null;
}

/**
 * Get all embedded font families
 */
export function getEmbeddedFontFamilies(): string[] {
  return Array.from(new Set(Object.values(fontEmbeds).map(f => f.family)));
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);

  const totalSize = Object.values(fontEmbeds).reduce((sum, font) => sum + font.size, 0);
  console.log(`\n✅ Generated ${OUTPUT_FILE}`);
  console.log(`📦 Total embedded fonts: ${Object.keys(fontEmbeds).length}`);
  console.log(`💾 Total size: ${(totalSize / 1024).toFixed(1)}KB\n`);
}

try {
  generateFontEmbeds();
} catch (error) {
  console.error('❌ Error generating font embeds:', error);
  process.exit(1);
}
